# Generated by Django 3.2.7 on 2021-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('pincode', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Amaravati\t'), ('Arunachal Pradesh', 'Itanagar'), ('Assam', 'Dispur'), ('Bihar', 'Patna'), ('Chhattisgarh', 'Raipur'), ('Goa', 'Panaji'), ('Gujarat', 'Gandhinagar')], max_length=120)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_location', models.CharField(max_length=120)),
                ('profile_image', models.ImageField(blank=True, upload_to='images')),
                ('job_state', models.CharField(max_length=20)),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
